### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fredcarle** [lazywei/go-opencv#83]
I tried to reproduce a C++ code that did motion detection using this package and I have a memory leak that I can't seem to find the source of. I'm not sure if it's from my code or from one of the bindings. Can someone look at my code and help me out with this? If it's not my code, maybe this will help find the possible source in the binding code.

https://gist.github.com/fredcarle/2b73b82ed2657b297824fe55caf94b52#file-motiondetect-go

**Comment by kevinabrandon** [comment]
How do you know there's a memory leak?  I've been running the nifty program for about 10 minutes now and I see no change in my memory usage.

**Comment by fredcarle** [comment]
I ran it all night long and accumulated 1GB of ram for that process.

**Comment by kevinabrandon** [comment]
I'll let it keep running and see if I can reproduce that.

**Comment by kevinabrandon** [comment]
It was indeed leaking and I found the source (hopefully it's the only one).

In detectMotion() you get the result's width and height by doing result.GetMat().Cols() and then result.GetMat().Rows().  Each time you do that you are creating a new Mat with the GetMat().  A full copy is made and is never released.

Instead you should simply do result.Width() and result.Height(), which isn't creating anything new.

**Comment by fredcarle** [comment]
Makes sense. I'm sad I didn't catch that one by myself. I was definitely skipping over this section thinking everything was OK. Thanks a lot for your help!

Do you think this piece of code could be a good example to add to the samples? Or do you have a better idea of a way to share it to help others?

**Comment by kevinabrandon** [comment]
Sure, I think this would work great as an example.  

I do have a few questions about the code:

1. Why use 3 images (previous, current and next) to test for changes?  Why not do only the current and next frame?  
2. What's the purpose of the Erode?  Simply make any changes smaller?  I guess it would kill any single pixel sized changes?
3. When you loop through the pixels, why is the increment += 2?  Doesn't that skip every other a bunch of the pixels as you're looking for changes?  Is it simply to speed up the search?
4. You have these x and y Start and Stops to define the region of interest.  Why not crop the frame using those values so that your processing is done on only that portion of the image.  If the region of interest becomes small, then changes outside the region will affect the stdDeviation calculation which may not be what you want.  If you intended to keep the region of interest large, over the entire image, then maybe they should be removed from the program to make things simpler. 

Also, here are some other suggestions (don't feel like you have to take them):

 - Have some of the variables controlled by trackbars.  Especially the maxDeviation and the thereIsMotion vars.  That way the user can adjust them while the program is running and see how sensitive the detection becomes.
 - Another idea would be to have the region of interest (xStart,xStop,yStart, and yStop) also controlled by trackbars, and then draw a different color rectangle showing the area that is under surveillance.  The user could then adjust the detection area after the program has started.
 - If you want, in detectionMotion(), you could use some of the code I pushed this morning to create a sequence of points for each detected change, and then pass that to BoundingRect() to create the red rectangle.  That way you don't have to keep track of Min and Max values.  This works just fine how it is though.
 - It would be cool to see the motion image after diffImg() is returned, and also after the final Erode().  You could have a trackbar that goes from 0-2.  If the trackbar is value is 0, then it shows the result image.  If its value is 1, then it shows the motion image after diffImg() returns.  If the value is 2, then it shows the motion image after Erode() returns.  That way the user can immediately see what each operation is doing.

Again, you don't have to do any of these things, I think it would work okay as is.

**Comment by fredcarle** [comment]
To answer your questions:

1. You can find the reason for this in this [paper](http://www-preview.ri.cmu.edu/pub_files/pub2/collins_robert_2000_1/collins_robert_2000_1.pdf), see section 3.1.1
2. Thats correct
3. Exactly. skipping a pixel wont affect the result but will speed up the process
4. You're right. The way I used it there isn't really useful but my plan is to later make it go around moving trees to avoid false positives. Good idea to trim the image though.

I'll definitely try to implement what you suggested. I'm a bit busy this weekend but I'll send the changes early next week.

Thanks again for your time @kevinabrandon
